import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const read = (relative: string) => readFileSync(join(root, relative), "utf8");

describe("checkout-replacement staging race harness", () => {
  it("exposes one dedicated zero-retry execution and read-only discovery", () => {
    const packageJson = read("package.json");
    const runner = read("scripts/run-checkout-replacement-race-staging-e2e.mjs");
    expect(packageJson).toContain('"test:e2e:staging:v2:checkout-replacement-race"');
    expect(packageJson).toContain('"test:e2e:staging:v2:checkout-replacement-race:list"');
    expect(runner).toContain('argument !== "--list"');
    expect(runner).toContain("release-b-checkout-replacement-race-v2.e2e.ts");
    expect(runner).toContain("preflight-checkout-replacement-race-staging.mjs");
  });

  it("preflights exact staging identity, empty floor, fresh fixture, bundle, and compatibility baseline", () => {
    const source = read("scripts/preflight-checkout-replacement-race-staging.mjs");
    expect(source).toContain("STAGING_PROJECT_REF");
    expect(source).toContain("PRODUCTION_PROJECT_REF");
    expect(source).toContain('role.data !== "admin"');
    expect(source).toContain("openSessions.data.length === 0");
    expect(source).toContain("openTabs.data.length === 0");
    expect(source).toContain("!reviewed.safeToRun || !evidence.safeToRun");
    expect(source).toContain("JSON.stringify(reviewed.identityCollisions)");
    expect(source).toContain("artifactCollisions.length === 0");
    expect(source).toContain('openingStock: 3, price: 50');
    expect(source).toContain('flag: "wx"');
    expect(source).toContain("reviewed_preflight_drift");
  });

  it("captures both UI commands once and submits them simultaneously against shared inventory", () => {
    const source = read("tests/e2e/staging/release-b-checkout-replacement-race-v2.e2e.ts");
    expect(source).toContain('name: "Finalize Customer Tab Bill"');
    expect(source).toContain('name: "Replace Issued Bill"');
    expect(source).toContain('await quantity.fill("2")');
    expect(source).toContain("checkoutCommand.captureCount()).toBe(1)");
    expect(source).toContain("replacementCommand.captureCount()).toBe(1)");
    expect(source).toContain("checkoutCommand.submit(checkoutEnvelope)");
    expect(source).toContain("replacementCommand.submit(replacementEnvelope)");
    expect(source).toContain('persistCheckpoint("setup-prepared"');
    expect(source).toContain('persistCheckpoint("fixture-created"');
    expect(source).toContain('persistCheckpoint("original-committed"');
    expect(source).toContain('persistCheckpoint("original-prepared"');
    expect(source).toContain('persistCheckpoint("checkout-item-added"');
    expect(source).toContain('await page.reload({ waitUntil: "domcontentloaded" })');
    expect(source).toContain("expect.poll(() => readPendingOperationalMutations(page)).toEqual([])");
    expect(source).toContain('await signIn(page, credentials("A"))');
    expect(source).toContain('await signIn(observer.page, credentials("B"))');
    expect(source).not.toContain('Promise.all([signIn(page, credentials("A")), signIn(observer.page, credentials("B"))])');
    expect(source.indexOf('persistCheckpoint("race-prepared"')).toBeLessThan(source.indexOf("checkoutCommand.submit(checkoutEnvelope)"));
    expect(source).toContain('persistCheckpoint("cleanup-acknowledged"');
    expect(source).toContain("raceSubmitted && !raceResolved");
    expect(source).toContain("command.settled");
    expect(source).toContain("quiescenceError");
    expect(source).toContain("target.close({ runBeforeUnload: false })");
    expect(source).toContain('flag: "wx"');
  });

  it("postflight proves bill links, stock arithmetic, actors, normalized-only finance, cleanup, and empty floor", () => {
    const source = read("scripts/reconcile-checkout-replacement-race-staging.mjs");
    expect(source).toContain('selected.phase === "final"');
    expect(source).toContain("Mutation results are not exact");
    expect(source).toContain('status: "needs_guarded_recovery"');
    expect(source).toContain("safeForAutomaticRetry: false");
    expect(source).toContain("safeForIdentityBoundCleanup");
    expect(source).toContain("expandCanonicalEvidence(mutationStatuses, events, audits)");
    expect(source).toContain("canonicalRecoveryReferencesAreExact");
    expect(source).toContain("status.changed_rows?.audit_logs");
    expect(source).toContain("Current staging actors do not match the immutable execution actors");
    expect(source).toContain("Original bill replacement link is incorrect");
    expect(source).toContain("Stock movement arithmetic is incorrect");
    expect(source).toContain("Replacement movement actor is incorrect");
    expect(source).toContain("Bill-line mapping is incorrect");
    expect(source).toContain("bill-line IDs are not exact");
    expect(source).toContain('expected.action === "bill_issued"');
    expect(source).toContain('expected.action === "bill_replaced"');
    expect(source).toContain("auditBill?.replace_reason");
    expect(source).toContain("event changed_rows mismatch");
    expect(source).toContain("An active reservation remains after both tabs closed");
    expect(source).toContain("Physical stock arithmetic is not exactly 3 - 1 - 1 - 1 = 0");
    expect(source).toContain("Archive event identity/type/actor is incorrect");
    expect(source).toContain("Archive audit identity/type/message/actor is incorrect");
    expect(source).toContain("Post-archive app_state version/hash changed");
    expect(source).toContain("Financial race changed app_state hash");
    expect(source).toContain("Only the exact archive compatibility write is expected after the race");
    expect(source).toContain("The staging floor is not empty");
    expect(source).toContain('flag: "wx"');
  });

  it("provides a separately gated identity-bound cleanup executor and exact cleanup postflight", () => {
    const packageJson = read("package.json");
    const runner = read("scripts/run-checkout-replacement-race-cleanup-staging-e2e.mjs");
    const scenario = read("tests/e2e/staging/release-b-checkout-replacement-race-cleanup.e2e.ts");
    const postflight = read("scripts/reconcile-checkout-replacement-race-cleanup-staging.mjs");
    expect(packageJson).toContain('"test:e2e:staging:v2:checkout-replacement-race:cleanup"');
    expect(packageJson).toContain('"test:db:staging:v2:checkout-replacement-race:cleanup-postflight"');
    expect(runner).toContain("safeForIdentityBoundCleanup !== true");
    expect(runner).toContain("safeForAutomaticRetry !== false");
    expect(runner).toContain("productionAllowed !== false");
    expect(runner).toContain("An explicit E2E_RUN_ID is required");
    expect(runner).toContain("Cleanup E2E_RUN_ID must differ from the fixture run identity");
    expect(runner).toContain("collectCollisions(artifactRoot)");
    expect(scenario).toContain("expect(identity.actorId).toBe(recovery.actors.origin)");
    expect(scenario).toContain("expect(observerIdentity.actorId).toBe(recovery.actors.observer)");
    expect(scenario).toContain('await signIn(page, credentials("A"))');
    expect(scenario).toContain('await signIn(observer.page, credentials("B"))');
    expect(scenario).not.toContain('Promise.all([signIn(page, credentials("A")), signIn(observer.page, credentials("B"))])');
    expect(scenario).toContain('expectExactAuthorizedRows(bills, recovery.bills ?? [], "bill_number")');
    expect(scenario).toContain('expectExactAuthorizedRows(openTabs, recovery.openTabs ?? [], "id")');
    expect(scenario).toContain("expect(stable(mutationStatuses)).toEqual(stable(recovery.mutationStatuses ?? []))");
    expect(scenario).toContain("status.changed_rows?.stock_movements");
    expect(scenario).toContain("openingStock + movements.reduce");
    expect(scenario).toContain('checkpointEvidence("prepared")');
    expect(scenario).toContain("for (const compatibilityTab of beforeCompatibilityTabs)");
    expect(scenario).toContain("expect(normalizedTab).toBeTruthy()");
    expect(scenario).toContain('checkpointEvidence(`reject-${index + 1}-acknowledged`)');
    expect(scenario).toContain('checkpointEvidence("archive-acknowledged")');
    expect(scenario).toContain('operation: "reject_customer_tab"');
    expect(scenario).toContain('operation: "archive_inventory_item"');
    expect(scenario).toContain('flag: "wx"');
    expect(postflight).toContain("Cleanup changed committed bills");
    expect(postflight).toContain("Cleanup changed reservation source rows");
    expect(postflight).toContain("Cleanup created or changed stock movements");
    expect(postflight).toContain("exactly once per acknowledged cleanup command");
    expect(postflight).toContain("Current staging actors do not match cleanup evidence actors");
    expect(postflight).toContain('expectedEventType = isArchive ? "admin_data_committed" : "reject_customer_tab"');
    expect(postflight).toContain("event.entity_type !== result.entity_type");
    expect(postflight).toContain("delete expectedEventChangedRows.operational_events");
    expect(postflight).toContain("result.changed_rows.operational_events, [result.event_id]");
    expect(postflight).toContain("released_continued_from_session_ids ?? []");
    expect(postflight).toContain("Rejected customer tab for ${customerName}. Reason: ${cleanupReason}");
    expect(postflight).toContain("Cleanup audit identity/type/message/actor is incorrect");
    expect(postflight).toContain("Cleanup compatibility customer tabs do not match normalized terminal states");
    expect(postflight).toContain('flag: "wx"');
  });
});
